spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: my_route
          uri: localhost:8001
          predicates:
            - My=Tom
server:
  port: 8000
