server:
  port: 8079

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/galaxy-captain/java-web-template/blob/master/framework-config/src/main/resources/my.properties