server:
  port: 8080

spring:
  application:
    name: framework-registry
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: ${management.context-path}/test
        health-check-interval: 5s